### PR TITLE
Breadth First Search and Merge Sort in C++

### PR DESCRIPTION
**Pull request by aryanlath**
I have added merge sort algorithm(MergeSort.cpp) in the C++ folder.

### CODE REVIEW

**Comment by aryanlath** [comment]
I have also added Breadth First Search in C++.

**Review by iParadocx — APPROVED** [review]
_Thank you for contribution_
_Give star :star: to this repository_

**Comment by aryanlath** [comment]
> _Thank you for contribution_ _Give star ⭐ to this repository_

Sure

**Comment by aryanlath** [comment]
Thank for considering my contribution

**Pull request merged**
