### PR TITLE
Bubble sort algorithm in JavaScript

### PR DESCRIPTION
**Pull request by ays14**

### CODE REVIEW

**Comment by ays14** [comment]
Solves issue no #47

**Review by iParadocx — CHANGES_REQUESTED** [review]
@ays14 Check the code, there is some issue.

**Comment by ays14** [comment]
@iParadocx please check now, earlier I was logging the answer but changed it to a return type method and hence missed to update the return into break statement. The solution is working now.

**Review by iParadocx — APPROVED** [review]
_Thank you for contribution_
_Give star :star: to this repository_

**Pull request merged**
